config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get 'home/index'
  root :to => 'home#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:id, :name, :title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<table style="width:100%">
  <tr>
    <td width="30%"><%= f.label :编号 %></td>
    <td><%= f.text_field :id %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :作者 %></td>
    <td><%= f.text_field :name %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :标题 %></td>
    <td><%= f.text_field :title %></td>
  <tr>
  <tr>
    <td width="30%"><%= f.label :内容 %></td>
    <td><%= f.text_area :content, :rows=>5 %></td>
  <tr>
</table>
<p> <%= f.submit %> </p>
<% end %>

app/views/articles/edit.html.erb
<p> <%= link_to '返回查看', @article %> |<%= link_to '返回列表', articles_path %> </p>
<fieldset>
  <legend>编辑文章内容</legend>
  <%= render 'form' %>
</fieldset>

app/views/articles/index.html.erb
<p>
       <%= link_to '添加一篇新的文章', new_article_path %>
 </p>
<fieldset>
        <legend>文章列表</legend>
<table style="width:100%">
  <tr>
    <th>编号</th>
    <th>标题</th>
    <th> 用户</th>
    <th colspan="3">操作</th>
  </tr>
<% @articles.each do |article| %>
  <tr>
    <td><%= article.id %></td>
    <td><%= article.title %></td>
    <td><%= article.name %></td>
    <td><%= link_to '查看详细信息', article %></td>
    <td><%= link_to '编辑', edit_article_path(article) %></td>
    <td><%= link_to '删除', article, :confirm => '确定要删除吗?', :method => :delete %></td>
  </tr>
<% end %>
</table>
</fieldset>

app/views/articles/new.html.erb
<p> <%= link_to '返回列表', articles_path %> </p>
<fieldset>
  <legend>添加一篇新的文章</legend>
  <%= render 'form' %>
</fieldset>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>
<fieldset>
  <legend>查看文章详细信息</legend>
  <br/>
  <h2> 标题：<%= @article.title %></h2>
  <p> 编号：<%= @article.id %> | 用户：<%= @article.name %> </p>
  <p> <b>内容：</b> <%= @article.content %> </p>
  <%= link_to '编辑内容', edit_article_path(@article) %> | <%= link_to '返回列表', articles_path %>
</fieldset>

app/views/home/index.html.erb
<h1>窗内网的空间</h1>
<h3>窗内网致力于免费网络教学,图书出版/署名,视频教程</h3>
<p>大家好，欢迎光临窗内网的个人空间。这是我的新blog，还正在完善呢。<br/>
可以到<a href="http://www.itzcn.com">窗内网网站</a>查看我的最新动态哦....
</p>
<p>
由此进入<%= link_to "文章管理", articles_path %> 页面。
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" type="text/css" href="/stylesheets/style.css" media="screen" />
  <title>窗内网的空间</title>
</head>
<body>
<div class="page_wrap clearfix">
  <div class="top"></div>
  <div class="header">
    <h1>窗内网的空间</h1>
    窗内网致力于免费网络教学,图书出版/署名,视频教程..... <img src="/images/tongue.gif" alt="" width="20" height="20" /></div>
  <div class="container clearfix">
    <div class="left_nav" id="nav">
      <div class="left_nav_top"></div>
      <ul>
        <li><a href="#">[1] 返回首页</a></li>
        <li><a href="#">[2] 我的博客</a></li>
        <li><a href="#">[3] 发表随笔</a></li>
        <li><a href="#">[4] 嘻哈相册</a></li>
        <li><a href="#">[5] 标签归类</a></li>
        <li><a href="#">[6] 个人档案</a></li>
        <li><a href="#">[7] 亲朋好友</a></li>
        <li><a href="#">[8] 看看微博</a></li>
      </ul>
      <div class="left_nav_bottom"></div>
    </div>
  <%= yield %>
  </div>
  <div class="bottom clearfix">
    <div class="footer clearfix"> Copyright, 2010 itZcn.com &nbsp;&#8226;&nbsp; Design
      by somboy </div>
  </div>
</div>
</body>
</html>